import { mkdir, readFile, writeFile, rm } from "node:fs/promises";
import { dirname, join, resolve, relative, isAbsolute } from "node:path";
import { fileURLToPath } from "node:url";
import { headingsFromMdx } from "../src/lib/headings.ts";
import { blogPosts } from "../src/content/blog/catalog.ts";
import {
  selectBlogPosts,
  readingMinutes,
  blogLocales,
} from "../src/content/blog/model.ts";
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const generated = join(root, "src/content/blog/.generated");
const previewDir = process.env.BLOG_PREVIEW_DIR;
if (previewDir && process.env.CI)
  throw new Error(
    "Private blog previews must not run in CI or deployment builds."
  );
let drafts = [];
if (previewDir) {
  drafts = JSON.parse(
    await readFile(join(resolve(previewDir), "posts.json"), "utf8")
  );
  if (drafts.some((p) => p.published || p.publishedAt))
    throw new Error(
      "Preview manuscripts must be unpublished and have no release date."
    );
}
const selected = selectBlogPosts(
  [...blogPosts, ...drafts],
  Boolean(previewDir)
);
const loaded = [];
// Validate every selected body before touching a previous preview.
for (const post of selected) {
  const base = drafts.includes(post)
    ? resolve(previewDir)
    : join(root, "src/content/blog/articles");
  const sources = {};
  for (const lang of blogLocales) {
    const file = resolve(base, post.editions[lang].body);
    const rel = relative(base, file);
    if (rel.startsWith("..") || isAbsolute(rel))
      throw new Error("Body escapes article directory");
    sources[lang] = await readFile(file, "utf8");
    const ids = headingsFromMdx(sources[lang]).map((h) => h.id);
    if (ids.some((id) => !id) || new Set(ids).size !== ids.length)
      throw new Error(`Duplicate or empty headings: ${post.slug}/${lang}`);
    if (!sources[lang].trim())
      throw new Error(`Empty ${lang} body: ${post.slug}`);
  }
  loaded.push({ post, sources });
}
let previous = [];
try {
  previous = JSON.parse(await readFile(join(generated, "routes.json"), "utf8"));
} catch (e) {
  if (e.code !== "ENOENT") throw e;
}
for (const path of previous) {
  const match = /^src\/app\/(?:\((en|pl)\)\/)?blog\/(en|pl)\/[a-z0-9-]+$/.exec(
    path
  );
  if (!match || (match[1] && match[1] !== match[2]))
    throw new Error("Invalid generated route manifest");
  await rm(join(root, path), { recursive: true, force: true });
}
await rm(generated, { recursive: true, force: true });
await mkdir(generated, { recursive: true });
const routes = [],
  visible = [];
for (const { post, sources } of loaded) {
  const entry = {
    ...post,
    preview: !post.published,
    readingMinutes: {
      en: readingMinutes(sources.en),
      pl: readingMinutes(sources.pl),
    },
  };
  visible.push(entry);
  for (const lang of blogLocales) {
    const route = `src/app/(${lang})/blog/${lang}/${post.slug}`;
    routes.push(route);
    const bodyName = `${post.slug}.${lang}.mdx`;
    await writeFile(join(generated, bodyName), sources[lang]);
    await mkdir(join(root, route, "card.jpg"), { recursive: true });
    await writeFile(
      join(root, route, "page.tsx"),
      `// Generated by prepare-blog; edit the catalog and MDX instead.\nimport Body from "@/content/blog/.generated/${bodyName}";\nimport { BlogArticle, articleMetadata } from "@/components/Blog/BlogArticle";\nexport const metadata = articleMetadata(${JSON.stringify(post.slug)}, "${lang}");\nexport default function Page() { return <BlogArticle slug=${JSON.stringify(post.slug)} locale="${lang}" Body={Body} />; }\n`
    );
    await writeFile(
      join(root, route, "card.jpg/route.tsx"),
      `// Generated by prepare-blog.\nimport { blogCard } from "@/components/Blog/BlogCard";\nexport const dynamic = "force-static";\nexport function GET() { return blogCard(${JSON.stringify(post.slug)}, "${lang}"); }\n`
    );
  }
}
await writeFile(
  join(generated, "posts.ts"),
  `// Generated; no manuscript text enters client code.\nimport type { VisiblePost } from "../types";\nexport const visiblePosts: VisiblePost[] = ${JSON.stringify(visible, null, 2)};\n`
);
await writeFile(join(generated, "routes.json"), JSON.stringify(routes));
console.log(
  `Blog: ${visible.length} article(s), ${routes.length} editions${previewDir ? " — PRIVATE PREVIEW, DO NOT DEPLOY" : " — production"}`
);
